name: eduparo
description: "Eduparo - Educational Quiz App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  flutter_markdown: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^3.0.3
  firebase_auth_mocks: ^0.14.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_symbol.png
    - assets/app_images/
    - assets/app_images/avatars/
    - assets/app_images/categories/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_400.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon_400.png"
  windows:
    generate: true
    image_path: "assets/icon_400.png"
  macos:
    generate: true
    image_path: "assets/icon_400.png"
  linux:
    generate: true
    image_path: "assets/icon_400.png"
